site_name: napari-google-drive
site_description: A simple plugin to use with napari
site_author: Tim Morello

theme: readthedocs


repo_url: https://github.com/tdmorello/napari-google-drive

pages:
- Home: index.md
